brand:
  name: Morphwear
menu-string: Menu

nav:
  - title: Features
    url: '#features'
  - title: About
    url: '#about'
  - title: Contact
    url: '#contact'
    
footer:
  cta-text: Sign-up to our email list to learn more
  button: Submit
  form-alert: Email submitted.

copyright: Copyright &copy; Morphwear LLC 2021

social-buttons:
  - icon: fa fa-twitter
    url: '#' 
  - icon: fa fa-instagram
    url: '#'

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: terms_of_use.html
  - title: Sitemap
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
